# Generated by Django 6.1.1 on 2026-09-30 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], max_length=1)),
                ('date', models.DateField()),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Bank', 'Bank')], max_length=20)),
                ('expense_category', models.CharField(choices=[('Housing', 'Housing'), ('Food', 'Food'), ('Transport', 'Transport'), ('Healthcare', 'Healthcare'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Miscellaneous', 'Miscellaneous')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
